export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";
export const START_CHAT_REDUCER_LOADING = "START_CHAT_REDUCER_LOADING";
export const SET_CURRENT_CHAT_USER = "SET_CURRENT_CHAT_USER";
export const CURRENT_CHAT_USER_HISTORY_MESSAGE = "CURRENT_CHAT_USER_HISTORY_MESSAGE"
export const CURRENT_CHAT_USER_HISTORY_MESSAGE_FAIL = "CURRENT_CHAT_USER_HISTORY_MESSAGE_FAIL"